server.port=8080
spring.application.name=formula1-be
server.servlet.context-path=/api

# --- MySQL (local) ---
spring.datasource.url=jdbc:mysql://localhost:3306/formula1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- MySQL (VM 192.168.1.65) ---
#spring.datasource.url=jdbc:mysql://192.168.1.65:3306/formula1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=f1_admin
#spring.datasource.password=adminf1123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Logging
logging.level.com.formula1=INFO
