export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/',
  LOGIN: '/login',
  DRIVERS: '/drivers',
  DRIVER_DETAIL: '/drivers/:tipoDoc/:numDoc',
  TEAMS: '/teams',
  TEAM_DETAIL: '/teams/:id',
  CIRCUITS: '/circuits',
  CIRCUIT_DETAIL: '/circuits/:id',
  SEASONS: '/seasons',
  SEASON_DETAIL: '/seasons/:year',
  RACES: '/races',
  RACE_DETAIL: '/races/:id',
  STATISTICS: '/statistics',
  HEAD_TO_HEAD: '/head-to-head',
  ADMIN: '/admin',
  ADMIN_PILOTOS: '/admin/pilotos',
  ADMIN_ESCUDERIAS: '/admin/escuderias',
  ADMIN_CIRCUITOS: '/admin/circuitos',
  ADMIN_TEMPORADAS: '/admin/temporadas',
  ADMIN_GPS: '/admin/gps',
  ADMIN_SESIONES: '/admin/sesiones',
  ADMIN_RESULTADOS_CARRERA: '/admin/resultados/carrera',
  ADMIN_RESULTADOS_CLASIFICACION: '/admin/resultados/clasificacion',
} as const;

export const buildPath = {
  driverDetail: (tipoDoc: string, numDoc: string) => `/drivers/${tipoDoc}/${numDoc}`,
  teamDetail: (id: number) => `/teams/${id}`,
  circuitDetail: (id: number) => `/circuits/${id}`,
  seasonDetail: (year: number) => `/seasons/${year}`,
  raceDetail: (id: number) => `/races/${id}`,
};
