export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  DRIVERS: '/drivers',
  DRIVER_DETAIL: '/drivers/:id',
  TEAMS: '/teams',
  TEAM_DETAIL: '/teams/:id',
  CIRCUITS: '/circuits',
  CIRCUIT_DETAIL: '/circuits/:id',
  SEASONS: '/seasons',
  SEASON_DETAIL: '/seasons/:year',
  RACES: '/races',
  RACE_DETAIL: '/races/:id',
  STATISTICS: '/statistics',
  HEAD_TO_HEAD: '/head-to-head',
  NOT_FOUND: '*',
} as const;

export const TEAM_COLORS: Record<string, string> = {
  // By official name (BE)
  'Oracle Red Bull Racing': '#3671C6',
  'Scuderia Ferrari': '#E8002D',
  'Mercedes-AMG Petronas Formula One Team': '#27F4D2',
  'McLaren Formula 1 Team': '#FF8000',
  'Aston Martin Aramco Cognizant Formula One Team': '#229971',
  'BWT Alpine F1 Team': '#FF87BC',
  'Williams Racing': '#64C4FF',
  'MoneyGram Haas F1 Team': '#B6BABD',
  'Scuderia AlphaTauri': '#6692FF',
  'Alfa Romeo F1 Team Stake': '#900000',
  // By code (BE)
  'RBR': '#3671C6',
  'FER': '#E8002D',
  'MER': '#27F4D2',
  'MCL': '#FF8000',
  'AMF': '#229971',
  'ALP': '#FF87BC',
  'WIL': '#64C4FF',
  'HAS': '#B6BABD',
  'ATH': '#6692FF',
  'ALR': '#900000',
  // English fallbacks
  'Red Bull Racing': '#3671C6',
  'Ferrari': '#E8002D',
  'Mercedes': '#27F4D2',
  'McLaren': '#FF8000',
  'Aston Martin': '#229971',
  'Alpine': '#FF87BC',
  'Williams': '#64C4FF',
  'Haas': '#B6BABD',
};

export const DRIVER_PHOTOS: Record<string, string> = {
  // Parrilla 2023 / 2024
  'VER': 'https://www.formula1.com/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/2col/image.png',
  'PER': 'https://www.formula1.com/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png.transform/2col/image.png',
  'HAM': 'https://www.formula1.com/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png.transform/2col/image.png',
  'RUS': 'https://www.formula1.com/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png.transform/2col/image.png',
  'LEC': 'https://www.formula1.com/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png.transform/2col/image.png',
  'SAI': 'https://www.formula1.com/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png.transform/2col/image.png',
  'NOR': 'https://www.formula1.com/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png.transform/2col/image.png',
  'PIA': 'https://www.formula1.com/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png.transform/2col/image.png',
  'ALO': 'https://www.formula1.com/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png.transform/2col/image.png',
  'STR': 'https://www.formula1.com/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png.transform/2col/image.png',
  'OCO': 'https://www.formula1.com/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png.transform/2col/image.png',
  'GAS': 'https://www.formula1.com/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png.transform/2col/image.png',
  'BOT': 'https://www.formula1.com/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png.transform/2col/image.png',
  'ZHO': 'https://www.formula1.com/content/dam/fom-website/drivers/G/GUAZHO01_Guanyu_Zhou/guazho01.png.transform/2col/image.png',
  'TSU': 'https://www.formula1.com/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png.transform/2col/image.png',
  'DEV': 'https://www.formula1.com/content/dam/fom-website/drivers/N/NYCDEV01_Nyck_de_Vries/nycdev01.png.transform/2col/image.png',
  'MAG': 'https://www.formula1.com/content/dam/fom-website/drivers/K/KEVMAG01_Kevin_Magnussen/kevmag01.png.transform/2col/image.png',
  'HUL': 'https://www.formula1.com/content/dam/fom-website/drivers/N/NICHUL01_Nico_Hulkenberg/nichul01.png.transform/2col/image.png',
  'ALB': 'https://www.formula1.com/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png.transform/2col/image.png',
  'SAR': 'https://www.formula1.com/content/dam/fom-website/drivers/L/LOGSAR01_Logan_Sargeant/logsar01.png.transform/2col/image.png',
  'RIC': 'https://www.formula1.com/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png.transform/2col/image.png',
  'LAW': 'https://www.formula1.com/content/dam/fom-website/drivers/L/LIALAW01_Liam_Lawson/lialaw01.png.transform/2col/image.png',
  'COL': 'https://www.formula1.com/content/dam/fom-website/drivers/F/FRACOL01_Franco_Colapinto/fracol01.png.transform/2col/image.png',
};

export const NATIONALITY_FLAGS: Record<string, string> = {
  // Spanish (from BE)
  'Holandesa': '🇳🇱',
  'Británica': '🇬🇧',
  'Monegasca': '🇲🇨',
  'Española': '🇪🇸',
  'Mexicana': '🇲🇽',
  'Australiana': '🇦🇺',
  'Francesa': '🇫🇷',
  'Alemana': '🇩🇪',
  'Canadiense': '🇨🇦',
  'Finlandesa': '🇫🇮',
  'Japonesa': '🇯🇵',
  'Estadounidense': '🇺🇸',
  'Tailandesa': '🇹🇭',
  'Danesa': '🇩🇰',
  'China': '🇨🇳',
  'Brasileña': '🇧🇷',
  'Italiana': '🇮🇹',
  'Argentina': '🇦🇷',
  'Austriaca': '🇦🇹',
  'Suiza': '🇨🇭',
  // Sin tilde (como vienen de la BD)
  'Britanica': '🇬🇧',
  'Espanola': '🇪🇸',
  'Neozelandes': '🇳🇿',
  // English fallbacks
  'Dutch': '🇳🇱',
  'British': '🇬🇧',
  'Monegasque': '🇲🇨',
  'Spanish': '🇪🇸',
  'Mexican': '🇲🇽',
  'Australian': '🇦🇺',
  'French': '🇫🇷',
  'German': '🇩🇪',
  'Canadian': '🇨🇦',
  'New Zealander': '🇳🇿',
};

export interface CircuitInfo {
  descripcion: string;
  mapaUrl: string;
  fotoUrl: string;
  primerGP: number;
  vueltas: number;
  recordVuelta?: string;
}

export const CIRCUIT_DATA: Record<string, CircuitInfo> = {
  'Bahrain International Circuit': {
    descripcion: 'Construido en el desierto de Sakhir en 2004, el Circuito Internacional de Baréin fue el primero en Oriente Medio en albergar un Gran Premio de Fórmula 1. Famoso por sus adelantamientos y su iluminación nocturna, sus 15 curvas ofrecen múltiples zonas de DRS que favorecen las batallas codo a codo.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Bahrain%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/1-bahrain.jpg.transform/9col/image.jpg',
    primerGP: 2004,
    vueltas: 57,
    recordVuelta: '1:31.447 (Pedro de la Rosa, 2005)',
  },
  'Jeddah Corniche Circuit': {
    descripcion: 'El Circuito de la Corniche de Jeddah es el segundo más rápido del calendario de F1. Inaugurado en 2021 y ubicado en el paseo marítimo de la ciudad, sus 27 curvas de alta velocidad con muros cercanos lo convierten en uno de los trazados más desafiantes y espectaculares de la parrilla.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Saudi%20Arabia%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/2-saudi-arabia.jpg.transform/9col/image.jpg',
    primerGP: 2021,
    vueltas: 50,
    recordVuelta: '1:30.734 (Lewis Hamilton, 2021)',
  },
  'Albert Park Circuit': {
    descripcion: 'Ubicado en Melbourne, el Circuito de Albert Park acoge tradicionalmente la carrera de apertura de la temporada de F1. Sus rectas largas y curvas rápidas alrededor de un lago artificial lo hacen favorito entre pilotos y aficionados. Fue renovado en 2022 para mejorar los adelantamientos.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Australia%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/3-australia.jpg.transform/9col/image.jpg',
    primerGP: 1996,
    vueltas: 58,
    recordVuelta: '1:20.235 (Charles Leclerc, 2022)',
  },
  'Circuit de Monaco': {
    descripcion: 'El Circuito de Mónaco es el más famoso e histórico del calendario de F1. Sus estrechas calles, túnel y chicanes hacen que sea prácticamente imposible adelantar, convirtiendo la clasificación en el factor decisivo. Desde 1950, este mítico trazado urbano sigue siendo la joya de la corona del automovilismo.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Monaco%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/8-monaco.jpg.transform/9col/image.jpg',
    primerGP: 1950,
    vueltas: 78,
    recordVuelta: '1:12.909 (Rubens Barrichello, 2004)',
  },
  'Silverstone Circuit': {
    descripcion: 'Silverstone es el hogar del automovilismo británico y uno de los circuitos más rápidos y técnicos del campeonato. Sus curvas de alta velocidad como Copse, Maggotts y Becketts exigen el máximo de habilidad a los pilotos. Fue sede del primer Gran Premio de F1 en la historia, en 1950.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Great%20Britain%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/10-great-britain.jpg.transform/9col/image.jpg',
    primerGP: 1950,
    vueltas: 52,
    recordVuelta: '1:27.097 (Max Verstappen, 2020)',
  },
  'Baku City Circuit': {
    descripcion: 'Circuito callejero de 6 km trazado a lo largo de la costa del Mar Caspio. Combina calles estrechas del casco histórico con una larga recta de 2.2 km junto al mar. Inaugurado en 2016.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Azerbaijan%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/4-azerbaijan.jpg.transform/9col/image.jpg',
    primerGP: 2017,
    vueltas: 51,
  },
  'Miami International Autodrome': {
    descripcion: 'Circuito semipermanente construido alrededor del Hard Rock Stadium. Inaugurado en 2022, cuenta con 19 curvas y tres zonas DRS en sus 5.4 km de longitud.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Miami%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/5-miami.jpg.transform/9col/image.jpg',
    primerGP: 2022,
    vueltas: 57,
  },
  'Circuit de Barcelona-Catalunya': {
    descripcion: 'Circuito permanente situado en Montmeló, cerca de Barcelona. Sede habitual de test de pretemporada de F1. Sus 16 curvas y 4.6 km exigen un equilibrio perfecto entre carga aerodinámica y velocidad punta.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Spain%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/9-spain.jpg.transform/9col/image.jpg',
    primerGP: 1991,
    vueltas: 66,
  },
  'Circuit Gilles Villeneuve': {
    descripcion: 'Circuito semipermanente en la isla Notre-Dame, Montreal. Homenaje al piloto canadiense Gilles Villeneuve. Sus largas rectas y chicanes finales lo convierten en un festival de adelantamientos y frenadas espectaculares.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Canada%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/7-canada.jpg.transform/9col/image.jpg',
    primerGP: 1978,
    vueltas: 70,
  },
  'Red Bull Ring': {
    descripcion: 'Circuito montañoso en Spielberg, Austria, con solo 10 curvas y 4.3 km. Sus rectas cortas y subidas pronunciadas generan batallas intensas. Reformado en 1996 y rebautizado en 2011 por Red Bull.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Austria%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/11-austria.jpg.transform/9col/image.jpg',
    primerGP: 1970,
    vueltas: 71,
  },
  'Hungaroring': {
    descripcion: 'Circuito permanente a 20 km de Budapest. Con 14 curvas y escasas zonas de adelantamiento, se asemeja a Mónaco sin muros. Fue sede del primer GP de Europa del Este detrás del Telón de Acero en 1986.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Hungary%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/12-hungary.jpg.transform/9col/image.jpg',
    primerGP: 1986,
    vueltas: 70,
  },
  'Circuit de Spa-Francorchamps': {
    descripcion: 'El circuito más mítico del automovilismo moderno. Sus 7 km atraviesan las Ardenas belgas con curvas legendarias como Eau Rouge y Raidillon. El clima es impredecible: puede llover en un sector y haber sol en el siguiente.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Belgium%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/13-belgium.jpg.transform/9col/image.jpg',
    primerGP: 1950,
    vueltas: 44,
  },
  'Circuit Zandvoort': {
    descripcion: 'Circuito costero en los Países Bajos, rodeado de dunas de arena. Regresó al calendario en 2021 tras 36 años de ausencia. Sus curvas peraltadas y 4.2 km crean una atmósfera única con una afición local apasionada.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Netherlands%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/14-netherlands.jpg.transform/9col/image.jpg',
    primerGP: 1952,
    vueltas: 72,
  },
  'Autodromo Nazionale Monza': {
    descripcion: 'El templo de la velocidad. Con una historia que se remonta a 1922, Monza es el circuito más rápido del calendario de F1. Sus largas rectas y chicanes generan velocidades punta superiores a 360 km/h y slipstream épico.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Italy%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/15-italy.jpg.transform/9col/image.jpg',
    primerGP: 1950,
    vueltas: 51,
    recordVuelta: '1:21.046 (Rubens Barrichello, 2004)',
  },
  'Marina Bay Street Circuit': {
    descripcion: 'Circuito nocturno callejero de Singapur, inaugurado en 2008. Sus 23 curvas a lo largo de la bahía iluminada crean un espectáculo visual sin igual. El calor, la humedad y la seguridad exigen una concentración extrema a los pilotos.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Singapore%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/16-singapore.jpg.transform/9col/image.jpg',
    primerGP: 2008,
    vueltas: 62,
  },
  'Suzuka Circuit': {
    descripcion: 'Circuito permanente icónico con un diseño en forma de ocho único en la F1. Construido en 1962 por Honda, cuenta con curvas legendarias como la horquilla, el Eses y la curva 130R.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Japan%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/17-japan.jpg.transform/9col/image.jpg',
    primerGP: 1987,
    vueltas: 53,
  },
  'Lusail International Circuit': {
    descripcion: 'Circuito permanente de Qatar, inaugurado en 2004 para MotoGP. Regresó al calendario de F1 en 2021. Sus largas curvas de alta velocidad y el calor nocturno del desierto suponen un reto físico enorme para los pilotos.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Qatar%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/18-qatar.jpg.transform/9col/image.jpg',
    primerGP: 2021,
    vueltas: 57,
  },
  'Circuit of the Americas': {
    descripcion: 'El primer circuito construido expresamente para la F1 en Estados Unidos, inaugurado en 2012 en Austin, Texas. Su diseño de Hermann Tilke incorpora referencias a los mejores tramos de Spa, Silverstone y Hockenheim.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/USA%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/19-united-states.jpg.transform/9col/image.jpg',
    primerGP: 2012,
    vueltas: 56,
  },
  'Autodromo Hermanos Rodriguez': {
    descripcion: 'Situado a 2240 metros de altitud en Ciudad de México, este circuito exige una configuración aerodinámica única. El Foro Sol, con capacidad para 50.000 espectadores, crea una atmósfera espectacular en el estadio.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Mexico%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/20-mexico.jpg.transform/9col/image.jpg',
    primerGP: 1963,
    vueltas: 71,
  },
  'Autodromo Jose Carlos Pace': {
    descripcion: 'Conocido como Interlagos, este circuito de São Paulo es legendario por sus cambios de nivel, el clima impredecible y el apasionado público brasileño. Fue escenario de muchas de las batallas más épicas de la historia de la F1.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Brazil%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/21-brazil.jpg.transform/9col/image.jpg',
    primerGP: 1973,
    vueltas: 71,
  },
  'Las Vegas Strip Circuit': {
    descripcion: 'Circuito nocturno trazado a lo largo de la famosa Strip de Las Vegas. Inaugurado en 2023, sus largas rectas frente a los hoteles y casinos icónicos crean una carrera única que combina deporte y espectáculo.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Las%20Vegas%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/22-las-vegas.jpg.transform/9col/image.jpg',
    primerGP: 2023,
    vueltas: 50,
  },
  'Yas Marina Circuit': {
    descripcion: 'Circuito permanente de Abu Dabi, diseñado por Hermann Tilke e inaugurado en 2009. Sede del Gran Premio final de temporada, con una puesta de sol única. Sus 16 curvas y el complejo del hotel Yas Viceroy lo hacen inconfundible.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Abu%20Dhabi%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2023/race-listing/23-abu-dhabi.jpg.transform/9col/image.jpg',
    primerGP: 2009,
    vueltas: 58,
  },
  'Shanghai International Circuit': {
    descripcion: 'Circuito permanente de Shanghái, diseñado por Hermann Tilke e inaugurado en 2004. Su trazado en forma de pala china con variadas exigencias técnicas y su recta trasera de 1.2 km para dos zonas DRS lo hacen muy técnico.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/China%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2024/race-listing/5-china.jpg.transform/9col/image.jpg',
    primerGP: 2004,
    vueltas: 56,
  },
  'Autodromo Enzo e Dino Ferrari': {
    descripcion: 'El circuito de Imola, en Emilia-Romaña, Italia, es uno de los más históricos y técnicos del mundo. Sus curvas rápidas como Tamburello y Acque Minerali son un homenaje a la esencia del automovilismo clásico.',
    mapaUrl: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Emilia%20Romagna%20carbon.png.transform/2col/image.png',
    fotoUrl: 'https://www.formula1.com/content/dam/fom-website/races/2024/race-listing/6-emilia-romagna.jpg.transform/9col/image.jpg',
    primerGP: 1980,
    vueltas: 63,
  },
};

export const SESSION_TYPES = {
  FP1: 'Free Practice 1',
  FP2: 'Free Practice 2',
  FP3: 'Free Practice 3',
  Q: 'Qualifying',
  SQ: 'Sprint Qualifying',
  S: 'Sprint',
  R: 'Race',
} as const;

export const POINTS_SYSTEM_2024 = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1];
